#!/bin/bash

echo "Configurando ambiente"

echo "Instlando Husky Hooks na pasta \".husky\" \n"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/z4nder/laravel-git-hooks/master/hooks/run)"

echo "Finalizado! 😎\n"