#!/bin/sh
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

NAME=$(git branch | grep '*' | sed 's/* //')

echo "Running pre-push hook on: ${BBlue}" $NAME "${NC}"


# 1. PHP Unit Tests
echo "${BBlue}1. Running Pest${NC}"
./vendor/bin/pest --stop-on-failure

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1... pest${NC}"
    exit 1
fi


# 2. Larastan
echo "${BBlue}2. Running Larastan${NC}"
php -d memory_limit=-1 ./vendor/bin/phpstan analyse --level=1

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... larastan${NC}"
    exit 1
fi